## Numpy Arrays

In [2]:
import numpy as np

### Creating NumPy Arrays

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

### arange

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

### rand

In [19]:
np.random.rand(2)

array([0.6997501 , 0.66247532])

In [20]:
np.random.rand(5,5)

array([[0.46664165, 0.22230078, 0.1855963 , 0.97499038, 0.23806471],
       [0.94277152, 0.79991659, 0.23139175, 0.04877854, 0.44892348],
       [0.88873534, 0.09244277, 0.14812541, 0.21132408, 0.42403401],
       [0.49926854, 0.40948256, 0.08636022, 0.81369792, 0.02714685],
       [0.28233848, 0.62860807, 0.68907471, 0.6283472 , 0.9776242 ]])

### randn

In [21]:
np.random.randn(2)

array([-1.99597316, -0.16357928])

In [22]:
np.random.randn(5,5)

array([[ 0.29350725,  2.45990528,  0.93987952,  0.84767663, -0.7011397 ],
       [-0.47855816, -0.47972632,  1.86199821, -0.02959632, -0.99336907],
       [ 0.20464293,  0.04877527,  1.37451878,  0.81440871, -1.12350694],
       [-0.42673364,  0.87781874, -0.89472432, -0.00490644, -0.17060991],
       [ 0.13709923,  0.11672131,  0.2102506 ,  0.22025775, -1.3080919 ]])

### randint

In [23]:
np.random.randint(1,100)

58

In [24]:
np.random.randint(1,100,10)

array([ 2, 97, 14, 24, 26, 38,  3,  8, 33,  8])

## Array Attributes and Methods

In [25]:
arr = np.arange(25)

In [26]:
ran_arr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ran_arr

array([27, 28,  8, 26, 16, 29,  5, 17, 47,  6])

## Reshape

Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

In [30]:
ran_arr

array([27, 28,  8, 26, 16, 29,  5, 17, 47,  6])

In [31]:
ran_arr.max()

47

In [32]:
ran_arr.argmax()

8

In [33]:
ran_arr.min()

5

In [34]:
ran_arr.argmin()

6

## Shape

In [35]:
# Vector
arr.shape

(25,)

In [36]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

In [40]:
arr.dtype

dtype('int64')