## Numpy array indexing

In this lecture, we will discuss how to select elements or groups of elements from a matrix.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing and selection

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting 

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_arr = arr[0:6]

In [12]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_arr[:] = 99

In [14]:
slice_arr

array([99, 99, 99, 99, 99, 99])

Now note that the changes also occur in our original matrix.

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

The data is not copied, it is a view of the original matrix! This avoids memory problems.

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D matrix

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[1][0]

20

In [22]:
arr_2d[1,0]

20

In [24]:
# (2,2) right
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr_2d[2]

array([35, 40, 45])

In [26]:
arr_2d[2,:]

array([35, 40, 45])

### "Fancy" indexing
Fancy statement allows you to select entire rows or columns of order.

In [27]:
arr2d = np.zeros((10,10))

In [31]:
arr_length = arr2d.shape[1]

In [33]:
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [34]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [35]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### Selection

In [36]:
arr = np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
bool_arr = arr > 4

In [40]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])